using Music;

namespace Music
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.panel3 = new System.Windows.Forms.Panel();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuButton27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.panel4 = new System.Windows.Forms.Panel();
            this.tbSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.openTimer = new System.Windows.Forms.Timer(this.components);
            this.tbRoomID = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.btJoinRoom = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btCreateRoom = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.panel1.SuspendLayout();
            this.panel4.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel3
            // 
            this.panel3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(18)))), ((int)(((byte)(22)))));
            this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel3.Location = new System.Drawing.Point(341, 0);
            this.panel3.Margin = new System.Windows.Forms.Padding(4);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(1058, 846);
            this.panel3.TabIndex = 3;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(16)))), ((int)(((byte)(18)))), ((int)(((byte)(22)))));
            this.panel1.Controls.Add(this.tbRoomID);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Controls.Add(this.btJoinRoom);
            this.panel1.Controls.Add(this.btCreateRoom);
            this.panel1.Controls.Add(this.bunifuButton27);
            this.panel1.Controls.Add(this.bunifuButton26);
            this.panel1.Controls.Add(this.bunifuButton21);
            this.panel1.Controls.Add(this.bunifuButton22);
            this.panel1.Controls.Add(this.panel4);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Margin = new System.Windows.Forms.Padding(4);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(341, 846);
            this.panel1.TabIndex = 0;
            // 
            // bunifuButton27
            // 
            this.bunifuButton27.AllowAnimations = true;
            this.bunifuButton27.AllowMouseEffects = true;
            this.bunifuButton27.AllowToggling = false;
            this.bunifuButton27.AnimationSpeed = 200;
            this.bunifuButton27.AutoGenerateColors = false;
            this.bunifuButton27.AutoRoundBorders = false;
            this.bunifuButton27.AutoSizeLeftIcon = true;
            this.bunifuButton27.AutoSizeRightIcon = true;
            this.bunifuButton27.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton27.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton27.BackgroundImage")));
            this.bunifuButton27.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.ButtonText = "Profile";
            this.bunifuButton27.ButtonTextMarginLeft = 0;
            this.bunifuButton27.ColorContrastOnClick = 45;
            this.bunifuButton27.ColorContrastOnHover = 45;
            this.bunifuButton27.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton27.CustomizableEdges = borderEdges3;
            this.bunifuButton27.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton27.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.DisabledFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton27.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton27.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton27.ForeColor = System.Drawing.Color.White;
            this.bunifuButton27.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton27.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton27.IconLeftPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.bunifuButton27.IconMarginLeft = 11;
            this.bunifuButton27.IconPadding = 15;
            this.bunifuButton27.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton27.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton27.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton27.IconSize = 25;
            this.bunifuButton27.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.IdleBorderRadius = 1;
            this.bunifuButton27.IdleBorderThickness = 1;
            this.bunifuButton27.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.IdleIconLeftImage = global::Music.Properties.Resources.baseline_person_white_48dp;
            this.bunifuButton27.IdleIconRightImage = null;
            this.bunifuButton27.IndicateFocus = false;
            this.bunifuButton27.Location = new System.Drawing.Point(55, 473);
            this.bunifuButton27.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuButton27.Name = "bunifuButton27";
            this.bunifuButton27.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.OnDisabledState.BorderRadius = 1;
            this.bunifuButton27.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.OnDisabledState.BorderThickness = 1;
            this.bunifuButton27.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton27.OnDisabledState.IconLeftImage = null;
            this.bunifuButton27.OnDisabledState.IconRightImage = null;
            this.bunifuButton27.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.onHoverState.BorderRadius = 1;
            this.bunifuButton27.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.onHoverState.BorderThickness = 1;
            this.bunifuButton27.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton27.onHoverState.IconLeftImage = null;
            this.bunifuButton27.onHoverState.IconRightImage = null;
            this.bunifuButton27.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.OnIdleState.BorderRadius = 1;
            this.bunifuButton27.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.OnIdleState.BorderThickness = 1;
            this.bunifuButton27.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton27.OnIdleState.IconLeftImage = global::Music.Properties.Resources.baseline_person_white_48dp;
            this.bunifuButton27.OnIdleState.IconRightImage = null;
            this.bunifuButton27.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.OnPressedState.BorderRadius = 1;
            this.bunifuButton27.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.OnPressedState.BorderThickness = 1;
            this.bunifuButton27.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton27.OnPressedState.IconLeftImage = null;
            this.bunifuButton27.OnPressedState.IconRightImage = null;
            this.bunifuButton27.Size = new System.Drawing.Size(241, 73);
            this.bunifuButton27.TabIndex = 9;
            this.bunifuButton27.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton27.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton27.TextMarginLeft = 0;
            this.bunifuButton27.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton27.UseDefaultRadiusAndThickness = true;
            this.bunifuButton27.Click += new System.EventHandler(this.bunifuButton27_Click_1);
            // 
            // bunifuButton26
            // 
            this.bunifuButton26.AllowAnimations = true;
            this.bunifuButton26.AllowMouseEffects = true;
            this.bunifuButton26.AllowToggling = false;
            this.bunifuButton26.AnimationSpeed = 200;
            this.bunifuButton26.AutoGenerateColors = false;
            this.bunifuButton26.AutoRoundBorders = false;
            this.bunifuButton26.AutoSizeLeftIcon = true;
            this.bunifuButton26.AutoSizeRightIcon = true;
            this.bunifuButton26.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton26.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton26.BackgroundImage")));
            this.bunifuButton26.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton26.ButtonText = "Playlists";
            this.bunifuButton26.ButtonTextMarginLeft = 0;
            this.bunifuButton26.ColorContrastOnClick = 45;
            this.bunifuButton26.ColorContrastOnHover = 45;
            this.bunifuButton26.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton26.CustomizableEdges = borderEdges4;
            this.bunifuButton26.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton26.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.DisabledFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton26.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton26.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton26.ForeColor = System.Drawing.Color.White;
            this.bunifuButton26.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton26.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton26.IconLeftPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.bunifuButton26.IconMarginLeft = 11;
            this.bunifuButton26.IconPadding = 15;
            this.bunifuButton26.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton26.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton26.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton26.IconSize = 25;
            this.bunifuButton26.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.IdleBorderRadius = 1;
            this.bunifuButton26.IdleBorderThickness = 1;
            this.bunifuButton26.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.IdleIconLeftImage = global::Music.Properties.Resources.baseline_queue_music_white_48dp;
            this.bunifuButton26.IdleIconRightImage = null;
            this.bunifuButton26.IndicateFocus = false;
            this.bunifuButton26.Location = new System.Drawing.Point(55, 391);
            this.bunifuButton26.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuButton26.Name = "bunifuButton26";
            this.bunifuButton26.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.OnDisabledState.BorderRadius = 1;
            this.bunifuButton26.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton26.OnDisabledState.BorderThickness = 1;
            this.bunifuButton26.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton26.OnDisabledState.IconLeftImage = null;
            this.bunifuButton26.OnDisabledState.IconRightImage = null;
            this.bunifuButton26.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.onHoverState.BorderRadius = 1;
            this.bunifuButton26.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton26.onHoverState.BorderThickness = 1;
            this.bunifuButton26.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton26.onHoverState.IconLeftImage = null;
            this.bunifuButton26.onHoverState.IconRightImage = null;
            this.bunifuButton26.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.OnIdleState.BorderRadius = 1;
            this.bunifuButton26.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton26.OnIdleState.BorderThickness = 1;
            this.bunifuButton26.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton26.OnIdleState.IconLeftImage = global::Music.Properties.Resources.baseline_queue_music_white_48dp;
            this.bunifuButton26.OnIdleState.IconRightImage = null;
            this.bunifuButton26.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.OnPressedState.BorderRadius = 1;
            this.bunifuButton26.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton26.OnPressedState.BorderThickness = 1;
            this.bunifuButton26.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton26.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton26.OnPressedState.IconLeftImage = null;
            this.bunifuButton26.OnPressedState.IconRightImage = null;
            this.bunifuButton26.Size = new System.Drawing.Size(241, 73);
            this.bunifuButton26.TabIndex = 8;
            this.bunifuButton26.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton26.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton26.TextMarginLeft = 0;
            this.bunifuButton26.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton26.UseDefaultRadiusAndThickness = true;
            this.bunifuButton26.Click += new System.EventHandler(this.bunifuButton26_Click_1);
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Rank";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges5;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 15;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.IdleBorderRadius = 1;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.IdleIconLeftImage = global::Music.Properties.Resources.baseline_album_white_48dp;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(60, 310);
            this.bunifuButton21.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.OnDisabledState.BorderRadius = 1;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.onHoverState.BorderRadius = 1;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.OnIdleState.BorderRadius = 1;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.IconLeftImage = global::Music.Properties.Resources.baseline_album_white_48dp;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.OnPressedState.BorderRadius = 1;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(241, 73);
            this.bunifuButton21.TabIndex = 4;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // bunifuButton22
            // 
            this.bunifuButton22.AllowAnimations = true;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = false;
            this.bunifuButton22.AnimationSpeed = 200;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = false;
            this.bunifuButton22.AutoSizeLeftIcon = true;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
            this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.ButtonText = "Home";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges6;
            this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.DisabledFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton22.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton22.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 15;
            this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton22.IconSize = 25;
            this.bunifuButton22.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.IdleBorderRadius = 1;
            this.bunifuButton22.IdleBorderThickness = 1;
            this.bunifuButton22.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.IdleIconLeftImage = global::Music.Properties.Resources.outline_mic_white_48dp;
            this.bunifuButton22.IdleIconRightImage = null;
            this.bunifuButton22.IndicateFocus = false;
            this.bunifuButton22.Location = new System.Drawing.Point(60, 230);
            this.bunifuButton22.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.OnDisabledState.BorderRadius = 1;
            this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnDisabledState.BorderThickness = 1;
            this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.onHoverState.BorderRadius = 1;
            this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.onHoverState.BorderThickness = 1;
            this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton22.onHoverState.IconLeftImage = null;
            this.bunifuButton22.onHoverState.IconRightImage = null;
            this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.OnIdleState.BorderRadius = 1;
            this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnIdleState.BorderThickness = 1;
            this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnIdleState.IconLeftImage = global::Music.Properties.Resources.outline_mic_white_48dp;
            this.bunifuButton22.OnIdleState.IconRightImage = null;
            this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.OnPressedState.BorderRadius = 1;
            this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnPressedState.BorderThickness = 1;
            this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.bunifuButton22.OnPressedState.IconLeftImage = null;
            this.bunifuButton22.OnPressedState.IconRightImage = null;
            this.bunifuButton22.Size = new System.Drawing.Size(241, 73);
            this.bunifuButton22.TabIndex = 2;
            this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            this.bunifuButton22.Click += new System.EventHandler(this.bunifuButton22_Click_1);
            // 
            // panel4
            // 
            this.panel4.BackgroundImage = global::Music.Properties.Resources.searchbarmusic;
            this.panel4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.panel4.Controls.Add(this.tbSearch);
            this.panel4.Controls.Add(this.bunifuImageButton1);
            this.panel4.Location = new System.Drawing.Point(16, 17);
            this.panel4.Margin = new System.Windows.Forms.Padding(4);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(297, 114);
            this.panel4.TabIndex = 0;
            // 
            // tbSearch
            // 
            this.tbSearch.AcceptsReturn = false;
            this.tbSearch.AcceptsTab = false;
            this.tbSearch.AnimationSpeed = 200;
            this.tbSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSearch.AutoSizeHeight = true;
            this.tbSearch.BackColor = System.Drawing.Color.Transparent;
            this.tbSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSearch.BackgroundImage")));
            this.tbSearch.BorderColorActive = System.Drawing.Color.Transparent;
            this.tbSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSearch.BorderColorHover = System.Drawing.Color.Transparent;
            this.tbSearch.BorderColorIdle = System.Drawing.Color.Transparent;
            this.tbSearch.BorderRadius = 1;
            this.tbSearch.BorderThickness = 1;
            this.tbSearch.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbSearch.DefaultText = "";
            this.tbSearch.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(26)))), ((int)(((byte)(36)))));
            this.tbSearch.ForeColor = System.Drawing.Color.White;
            this.tbSearch.HideSelection = true;
            this.tbSearch.IconLeft = null;
            this.tbSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSearch.IconPadding = 10;
            this.tbSearch.IconRight = null;
            this.tbSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSearch.Lines = new string[0];
            this.tbSearch.Location = new System.Drawing.Point(72, 33);
            this.tbSearch.Margin = new System.Windows.Forms.Padding(4);
            this.tbSearch.MaxLength = 32767;
            this.tbSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSearch.Modified = false;
            this.tbSearch.Multiline = false;
            this.tbSearch.Name = "tbSearch";
            stateProperties1.BorderColor = System.Drawing.Color.Transparent;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Transparent;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Transparent;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(26)))), ((int)(((byte)(36)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSearch.OnIdleState = stateProperties4;
            this.tbSearch.Padding = new System.Windows.Forms.Padding(4);
            this.tbSearch.PasswordChar = '\0';
            this.tbSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSearch.PlaceholderText = "";
            this.tbSearch.ReadOnly = false;
            this.tbSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSearch.SelectedText = "";
            this.tbSearch.SelectionLength = 0;
            this.tbSearch.SelectionStart = 0;
            this.tbSearch.ShortcutsEnabled = true;
            this.tbSearch.Size = new System.Drawing.Size(171, 44);
            this.tbSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSearch.TabIndex = 1;
            this.tbSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSearch.TextMarginBottom = 0;
            this.tbSearch.TextMarginLeft = 3;
            this.tbSearch.TextMarginTop = 1;
            this.tbSearch.TextPlaceholder = "";
            this.tbSearch.UseSystemPasswordChar = false;
            this.tbSearch.WordWrap = true;
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(26)))), ((int)(((byte)(26)))), ((int)(((byte)(36)))));
            this.bunifuImageButton1.BackgroundImage = global::Music.Properties.Resources.baseline_search_white_48dp1;
            this.bunifuImageButton1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.bunifuImageButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.ErrorImage = null;
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.Image = global::Music.Properties.Resources.baseline_search_white_48dp;
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 0;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(32, 30);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(33, 31);
            this.bunifuImageButton1.InitialImage = null;
            this.bunifuImageButton1.Location = new System.Drawing.Point(247, 42);
            this.bunifuImageButton1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = false;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = true;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(33, 31);
            this.bunifuImageButton1.TabIndex = 1;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 0;
            this.bunifuImageButton1.ZoomSpeed = 10;
            this.bunifuImageButton1.Click += new System.EventHandler(this.bunifuImageButton1_Click);
            // 
            // openTimer
            // 
            this.openTimer.Enabled = true;
            this.openTimer.Tick += new System.EventHandler(this.openTimer_Tick);
            // 
            // tbRoomID
            // 
            this.tbRoomID.Location = new System.Drawing.Point(112, 653);
            this.tbRoomID.Name = "tbRoomID";
            this.tbRoomID.Size = new System.Drawing.Size(164, 22);
            this.tbRoomID.TabIndex = 182;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(19, 649);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(87, 25);
            this.label1.TabIndex = 181;
            this.label1.Text = "Room ID";
            // 
            // btJoinRoom
            // 
            this.btJoinRoom.AllowAnimations = true;
            this.btJoinRoom.AllowMouseEffects = true;
            this.btJoinRoom.AllowToggling = false;
            this.btJoinRoom.AnimationSpeed = 200;
            this.btJoinRoom.AutoGenerateColors = false;
            this.btJoinRoom.AutoRoundBorders = false;
            this.btJoinRoom.AutoSizeLeftIcon = true;
            this.btJoinRoom.AutoSizeRightIcon = true;
            this.btJoinRoom.BackColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.BackColor1 = System.Drawing.Color.Transparent;
            this.btJoinRoom.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btJoinRoom.BackgroundImage")));
            this.btJoinRoom.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btJoinRoom.ButtonText = "Join Room";
            this.btJoinRoom.ButtonTextMarginLeft = 0;
            this.btJoinRoom.ColorContrastOnClick = 45;
            this.btJoinRoom.ColorContrastOnHover = 45;
            this.btJoinRoom.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btJoinRoom.CustomizableEdges = borderEdges1;
            this.btJoinRoom.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btJoinRoom.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.DisabledFillColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.btJoinRoom.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btJoinRoom.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btJoinRoom.ForeColor = System.Drawing.Color.White;
            this.btJoinRoom.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btJoinRoom.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btJoinRoom.IconLeftPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btJoinRoom.IconMarginLeft = 11;
            this.btJoinRoom.IconPadding = 15;
            this.btJoinRoom.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btJoinRoom.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btJoinRoom.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btJoinRoom.IconSize = 25;
            this.btJoinRoom.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.IdleBorderRadius = 1;
            this.btJoinRoom.IdleBorderThickness = 1;
            this.btJoinRoom.IdleFillColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.IdleIconLeftImage = null;
            this.btJoinRoom.IdleIconRightImage = null;
            this.btJoinRoom.IndicateFocus = false;
            this.btJoinRoom.Location = new System.Drawing.Point(46, 678);
            this.btJoinRoom.Margin = new System.Windows.Forms.Padding(4);
            this.btJoinRoom.Name = "btJoinRoom";
            this.btJoinRoom.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.OnDisabledState.BorderRadius = 1;
            this.btJoinRoom.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btJoinRoom.OnDisabledState.BorderThickness = 1;
            this.btJoinRoom.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.btJoinRoom.OnDisabledState.IconLeftImage = null;
            this.btJoinRoom.OnDisabledState.IconRightImage = null;
            this.btJoinRoom.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.onHoverState.BorderRadius = 1;
            this.btJoinRoom.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btJoinRoom.onHoverState.BorderThickness = 1;
            this.btJoinRoom.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.btJoinRoom.onHoverState.IconLeftImage = null;
            this.btJoinRoom.onHoverState.IconRightImage = null;
            this.btJoinRoom.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.OnIdleState.BorderRadius = 1;
            this.btJoinRoom.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btJoinRoom.OnIdleState.BorderThickness = 1;
            this.btJoinRoom.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btJoinRoom.OnIdleState.IconLeftImage = null;
            this.btJoinRoom.OnIdleState.IconRightImage = null;
            this.btJoinRoom.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.OnPressedState.BorderRadius = 1;
            this.btJoinRoom.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btJoinRoom.OnPressedState.BorderThickness = 1;
            this.btJoinRoom.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btJoinRoom.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.btJoinRoom.OnPressedState.IconLeftImage = null;
            this.btJoinRoom.OnPressedState.IconRightImage = null;
            this.btJoinRoom.Size = new System.Drawing.Size(241, 47);
            this.btJoinRoom.TabIndex = 180;
            this.btJoinRoom.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btJoinRoom.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btJoinRoom.TextMarginLeft = 0;
            this.btJoinRoom.TextPadding = new System.Windows.Forms.Padding(0);
            this.btJoinRoom.UseDefaultRadiusAndThickness = true;
            // 
            // btCreateRoom
            // 
            this.btCreateRoom.AllowAnimations = true;
            this.btCreateRoom.AllowMouseEffects = true;
            this.btCreateRoom.AllowToggling = false;
            this.btCreateRoom.AnimationSpeed = 200;
            this.btCreateRoom.AutoGenerateColors = false;
            this.btCreateRoom.AutoRoundBorders = false;
            this.btCreateRoom.AutoSizeLeftIcon = true;
            this.btCreateRoom.AutoSizeRightIcon = true;
            this.btCreateRoom.BackColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.BackColor1 = System.Drawing.Color.Transparent;
            this.btCreateRoom.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btCreateRoom.BackgroundImage")));
            this.btCreateRoom.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreateRoom.ButtonText = "Create Room";
            this.btCreateRoom.ButtonTextMarginLeft = 0;
            this.btCreateRoom.ColorContrastOnClick = 45;
            this.btCreateRoom.ColorContrastOnHover = 45;
            this.btCreateRoom.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btCreateRoom.CustomizableEdges = borderEdges2;
            this.btCreateRoom.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btCreateRoom.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.DisabledFillColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.btCreateRoom.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btCreateRoom.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btCreateRoom.ForeColor = System.Drawing.Color.White;
            this.btCreateRoom.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btCreateRoom.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btCreateRoom.IconLeftPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btCreateRoom.IconMarginLeft = 11;
            this.btCreateRoom.IconPadding = 15;
            this.btCreateRoom.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btCreateRoom.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btCreateRoom.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btCreateRoom.IconSize = 25;
            this.btCreateRoom.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.IdleBorderRadius = 1;
            this.btCreateRoom.IdleBorderThickness = 1;
            this.btCreateRoom.IdleFillColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.IdleIconLeftImage = null;
            this.btCreateRoom.IdleIconRightImage = null;
            this.btCreateRoom.IndicateFocus = false;
            this.btCreateRoom.Location = new System.Drawing.Point(80, 562);
            this.btCreateRoom.Margin = new System.Windows.Forms.Padding(4);
            this.btCreateRoom.Name = "btCreateRoom";
            this.btCreateRoom.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.OnDisabledState.BorderRadius = 1;
            this.btCreateRoom.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreateRoom.OnDisabledState.BorderThickness = 1;
            this.btCreateRoom.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.btCreateRoom.OnDisabledState.IconLeftImage = null;
            this.btCreateRoom.OnDisabledState.IconRightImage = null;
            this.btCreateRoom.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.onHoverState.BorderRadius = 1;
            this.btCreateRoom.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreateRoom.onHoverState.BorderThickness = 1;
            this.btCreateRoom.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.btCreateRoom.onHoverState.IconLeftImage = null;
            this.btCreateRoom.onHoverState.IconRightImage = null;
            this.btCreateRoom.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.OnIdleState.BorderRadius = 1;
            this.btCreateRoom.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreateRoom.OnIdleState.BorderThickness = 1;
            this.btCreateRoom.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btCreateRoom.OnIdleState.IconLeftImage = null;
            this.btCreateRoom.OnIdleState.IconRightImage = null;
            this.btCreateRoom.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.OnPressedState.BorderRadius = 1;
            this.btCreateRoom.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btCreateRoom.OnPressedState.BorderThickness = 1;
            this.btCreateRoom.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btCreateRoom.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(216)))), ((int)(((byte)(87)))));
            this.btCreateRoom.OnPressedState.IconLeftImage = null;
            this.btCreateRoom.OnPressedState.IconRightImage = null;
            this.btCreateRoom.Size = new System.Drawing.Size(154, 71);
            this.btCreateRoom.TabIndex = 179;
            this.btCreateRoom.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btCreateRoom.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btCreateRoom.TextMarginLeft = 0;
            this.btCreateRoom.TextPadding = new System.Windows.Forms.Padding(0);
            this.btCreateRoom.UseDefaultRadiusAndThickness = true;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1399, 846);
            this.Controls.Add(this.panel3);
            this.Controls.Add(this.panel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Soul Sound";
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel4.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private USCRankMusic uscRankMusic1;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.Panel panel4;
        private Bunifu.UI.WinForms.BunifuTextBox tbSearch;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton26;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton27;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Timer openTimer;
        private System.Windows.Forms.TextBox tbRoomID;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btJoinRoom;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btCreateRoom;
    }
}
